### ISSUE TITLE
set snakemake==7.32 in flanking-regions.yaml

### ISSUE THREAD

**Issue by mpgriesh** [liampshaw/mobile-gene-regions#17]
Syntax of several flags was deprecated in the update from Snakemake 7 to 8. Without specifying the snakemake version, the yaml file leads to version 8.25.2 installing currently and the code fails.

**Comment by liampshaw** [comment]
Thanks! This is very helpful. Version is now specified in `flanking-regions.yaml` in commit `8b532ffd6dcd49af1fc0e8dda5ac70c515e9302e` and I have added a note to the README. That worked for me so I've closed the issue - if you encounter difficulties please raise again.
